### ISSUE TITLE
Implement methods to create or import accounts

### ISSUE THREAD

**Issue by centaur1** [Tschaul/twister-lib-js#5]
Implement methods to create or import accounts

I am creating issues here so that we can create a bounty for them as with twister-core compiling issues a few weeks ago.

**Comment by fredericomba** [comment]
Hello. I have seen the bounties regarding this project posted, and I'm interested on them. I'm knowledgeable about JavaScript, and I think I'm able to help. In how much time do you expect this to be done?

**Comment by centaur1** [comment]
Hi, I am not sure how much time it would take, but have you looked at the code at all?

**Comment by fredericomba** [comment]
No, I have not looked into the code yet, but I'm always looking for opportunities to make some money here and there. Because my style of getting income is like hunter-gathering, sometimes there are "winter periods" where I can't find work. These winter periods are useful for looking for jobs that may make my idle time into productive time.

It seems that these two bounties (each one worth about US$ 250) have not attracted other people, so I'll stay around and look at the code.

**Comment by centaur1** [comment]
Yeah, if you have an idea of the amount of time it might take, perhaps post it here.  :-)

**Comment by gabrielhesposito** [comment]
I've started working on this here https://github.com/Tschaul/twister-lib-js/pull/9

**Comment by gabrielhesposito** [comment]
@centaur1  my pr is ready for initial review, https://github.com/Tschaul/twister-lib-js/pull/9
happy to make any changes

**Comment by centaur1** [comment]
I am not sure if I can release the bounty or not.  I don't see how on bountysource yet

**Comment by centaur1** [comment]
It was definitely merged, but I don't see how to release the bounty yet.  The other one was obvious how to do so, but I haven't seen how to do so here.

**Comment by gabrielhesposito** [comment]
@centaur1 I believe by resolving the issue the bounty is released.

**Comment by gabrielhesposito** [comment]
```
You will be able to claim this bounty as soon as the original issue is marked as closed. 
```
